# Generated by Django 3.1.1 on 2020-09-11 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_country',
            field=models.CharField(choices=[('NL', 'Netherlands'), ('BE', 'Belgium')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_street1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_street2',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='company_zipcode',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
