# Generated by Django 3.1.1 on 2020-09-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200911_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_country',
            field=models.CharField(choices=[('NL', 'Netherlands'), ('BE', 'Belgium')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_houseno',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
