# Generated by Django 3.1.1 on 2020-09-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200911_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_city',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_houseno',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_street',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
