# Generated by Django 3.1.1 on 2020-09-12 05:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_resourceipv4'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceIPv6',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_prefix', models.CharField(blank=True, max_length=500)),
                ('resource_country', models.CharField(choices=[('NL', 'Netherlands'), ('BE', 'Belgium')], max_length=50, null=True)),
                ('resource_netname', models.CharField(blank=True, max_length=500)),
                ('resource_description', models.CharField(blank=True, max_length=500)),
                ('resource_organisation', models.CharField(blank=True, max_length=500)),
                ('resource_admin_c', models.CharField(blank=True, max_length=500)),
                ('resource_tech_c', models.CharField(blank=True, max_length=500)),
                ('resource_mnt_lower', models.CharField(blank=True, max_length=500)),
                ('resource_mnt_routes', models.CharField(blank=True, max_length=500)),
                ('resource_mnt_domains', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
