# Generated by Django 3.1.1 on 2020-09-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200912_0610'),
    ]

    operations = [
        migrations.AddField(
            model_name='peers',
            name='remote_asn',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='peers',
            name='peer_email',
            field=models.EmailField(max_length=254),
        ),
    ]
